
conda activate rlbench

export LIBGL_ALWAYS_SOFTWARE=1
export CPATH=$CONDA_PREFIX/include
export COPPELIASIM_ROOT=${HOME}/CoppeliaSim
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$COPPELIASIM_ROOT
export QT_QPA_PLATFORM_PLUGIN_PATH=$COPPELIASIM_ROOT
